version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "twitter-following-tracker"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-o1x3an7gvtpd"
s3_prefix = "twitter-following-tracker"
region = "eu-west-3"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BearerToken=\"AAAAAAAAAAAAAAAAAAAAAI3IiAEAAAAAjIFb3%2FK52UzrapilHCG%2BU9O6dj0%3Digh4LiT74EQfT570lkXpH3DUhNswwjMFDMP3p1uXt1vJlUyxAW\" TwitterAuthorizationSchedule=\"Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA\" TwitterAuthorizationCrud=\"Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA\" XCsrfTokenSchedule=\"3634d18a6f51acd874306fdd16200f150a3767e2eb02acf3e57ae7814cf9bb72045549dfa22d18812ee6677a4c78b7fd817b0aa37a19a6c36060223c7f88e023af83f01acfaca553485fb6a95b04ac8d\" XCsrfTokenCrud=\"a91309a0af655d8c62d592a885881c62fc19e7467f9b5aa030eb1d7fac3d1a48e2f0f2cc7306e1c778934b22997d89d0fe9a7741f10270e1601769cf0258cb501e618649c60e1aa9888b96689e19704c\" CookieAuthTokenSchedule=\"e1f74fba778c9af7fe6ffcd1e46ffbd11b10d0cf\" CookieAuthTokenCrud=\"51febdf7b43ec6654bd93b60386cc409229e01cc\" TelegramBotToken=\"bot5665851743:AAFLyINyFjnPRB3Ug_ucHQsfOyGqNbTHo_o\""
image_repositories = []
